// Generated by scripts/build-audio-sprite.mjs. Do not edit by hand.
import type { SampleZone } from './audio';

export const YAMAHA_U1_ZONES = [
  {
    "loKey": 0,
    "hiKey": 30,
    "rootKey": 24,
    "offsetSeconds": 0,
    "durationSeconds": 6.955147392290249
  },
  {
    "loKey": 31,
    "hiKey": 35,
    "rootKey": 31,
    "offsetSeconds": 7.012426303854875,
    "durationSeconds": 6.933310657596372
  },
  {
    "loKey": 36,
    "hiKey": 42,
    "rootKey": 36,
    "offsetSeconds": 14.001632653061224,
    "durationSeconds": 7.169478458049887
  },
  {
    "loKey": 43,
    "hiKey": 47,
    "rootKey": 43,
    "offsetSeconds": 21.223038548752836,
    "durationSeconds": 6.885850340136054
  },
  {
    "loKey": 48,
    "hiKey": 54,
    "rootKey": 48,
    "offsetSeconds": 28.16580498866213,
    "durationSeconds": 7.167097505668934
  },
  {
    "loKey": 55,
    "hiKey": 59,
    "rootKey": 55,
    "offsetSeconds": 35.38721088435374,
    "durationSeconds": 7.201043083900227
  },
  {
    "loKey": 60,
    "hiKey": 66,
    "rootKey": 60,
    "offsetSeconds": 42.6550566893424,
    "durationSeconds": 6.985374149659864
  },
  {
    "loKey": 67,
    "hiKey": 71,
    "rootKey": 67,
    "offsetSeconds": 49.69070294784581,
    "durationSeconds": 6.901632653061225
  },
  {
    "loKey": 72,
    "hiKey": 78,
    "rootKey": 72,
    "offsetSeconds": 56.65668934240363,
    "durationSeconds": 6.7818140589569165
  },
  {
    "loKey": 79,
    "hiKey": 83,
    "rootKey": 79,
    "offsetSeconds": 63.506575963718824,
    "durationSeconds": 5.932698412698413
  },
  {
    "loKey": 84,
    "hiKey": 90,
    "rootKey": 84,
    "offsetSeconds": 69.49732426303855,
    "durationSeconds": 5.015510204081632
  },
  {
    "loKey": 91,
    "hiKey": 95,
    "rootKey": 91,
    "offsetSeconds": 74.55927437641724,
    "durationSeconds": 3.1927437641723357
  },
  {
    "loKey": 96,
    "hiKey": 102,
    "rootKey": 96,
    "offsetSeconds": 77.81006802721089,
    "durationSeconds": 2.136235827664399
  },
  {
    "loKey": 102,
    "hiKey": 127,
    "rootKey": 103,
    "offsetSeconds": 79.99274376417233,
    "durationSeconds": 1.8459863945578232
  }
] as const satisfies readonly SampleZone[];
